version: 2
updates:
  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: monthly
  - package-ecosystem: swift
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: monthly
